[versions]
agp = "8.5.2"
bugseeAndroid = "5.6.0"
credentialsPlayServicesAuth = "1.3.0"
firebaseAppdistribution = "16.0.0-beta14"
firebaseBom = "33.5.1"
flexbox = "3.0.0"
glide = "4.16.0"
compiler = "4.16.0"
googleid = "1.1.1"
gson = "2.11.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lottie = "6.5.2"
material = "1.12.0"
constraintlayout = "2.2.0"
chatSdkAndroid = "4.0.10"
callsSdkAndroid = "4.0.6"
cometchat-ui-kit = "5.0.0"
playServicesAuth = "21.2.0"
recyclerview = "1.3.2"
kotlin = "1.9.24"
coreKtx = "1.15.0"

[libraries]
bugsee-android = { module = "com.bugsee:bugsee-android", version.ref = "bugseeAndroid" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentialsPlayServicesAuth" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-appdistribution = { module = "com.google.firebase:firebase-appdistribution", version.ref = "firebaseAppdistribution" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.3" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
chat-sdk-android = { group = "com.cometchat", name = "chat-sdk-android", version.ref = "chatSdkAndroid" }
calls-sdk-android = { group = "com.cometchat", name = "calls-sdk-android", version.ref = "callsSdkAndroid" }
cometchat-ui-kit = { module = "com.cometchat:chat-uikit-android", version.ref = "cometchat-ui-kit" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

